version: '3'

services:
  api:
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=ds115360.mlab.com
      - DATABASE_PORT=15360
      - DATABASE_NAME=cms-dev
      - DATABASE_USERNAME=cms
      - DATABASE_PASSWORD=WxSauR5318Ld
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      - /usr/src/api/strapi-app/node_modules
    restart: always
